name: TestPlugin
version: '${project.version}'
main: me.thatonedevil.test.Main
api-version: 1.18
authors: [ ThatOneDevil ]
description: Cool test plugin
commands:
  punish:
    description: Punish command for staff
    permission: punish
  pmessage:
    aliases: pmsg
    description: Sends a private message to someone
  preply:
    description: Reply to the private message sent by someone
  test:
  menu:
  info:


